# 
secrets:
  docker: "foo"

# app
wordpressUsername: app1
wordpressPassword: "app1p@i%22323ex"

# smtp settings
smtpHost: "smtp.mandrillapp.com"
smtpPort: "587"
smtpUser: "app1@app1.com"
smtpPassword: "app1p@KPelNtA"


extraEnvVars:
  - name: kemooo
    value: kemoooapp1
  - name: CLIENT_NAME
    value: app1
  - name: AWS_S3_BUCKET
    value: app1
  - name: AWS_ACCESS_KEY_ID
    value: app1
  - name: AWS_SECRET_ACCESS_KEY
    value: app1
  - name: DB_ROOT_PASS
    value: app1@d24e7f
  - name: DB_HOST
    value: app1-mariadb
  - name: DB_NAME
    value: app1
  - name: DB_PASS
    value: app1@3e5F0f
  - name: DB_USER
    value: app1
